"""add_structured_issues

Revision ID: 3b832fc0f63d
Revises: 49c2a9c9e9ee
Create Date: 2026-06-03 10:28:33.957702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b832fc0f63d'
down_revision: Union[str, Sequence[str], None] = '49c2a9c9e9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('structured_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('evaluations_session_id_key'), 'evaluations', type_='unique')
    op.drop_index(op.f('ix_evaluations_session_id'), table_name='evaluations')
    op.create_index(op.f('ix_evaluations_session_id'), 'evaluations', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_session_id'), table_name='evaluations')
    op.create_index(op.f('ix_evaluations_session_id'), 'evaluations', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('evaluations_session_id_key'), 'evaluations', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('evaluations', 'structured_issues')
    # ### end Alembic commands ###
